### ISSUE TITLE
无法适配BUG

### ISSUE THREAD

**Issue by tcqq** [zhengjingle/Autolayout#5]
-

**Comment by tcqq** [comment]
![image](https://user-images.githubusercontent.com/10644057/37735063-e5c1e5d8-2d87-11e8-86b6-c786ef841296.png)
如果黄色框框中使用displayHeight后：
设计稿尺寸填写为：1080x1920，然后我在布局中创建一个View，高度设置成1920px，现在运行之后那个View的高度和任何屏幕的高度都相等，因为displayHeight的值没有算上“状态栏”和“导航栏”的高度。

现在1080x1920的设计稿里面有一个控件，它的高度是63px，然后我新建一个布局，在这个布局里面添加一个View，并将View的高度设置成63px，然后我运行在1080x1920的设备上，但是那个控件最后显示出来高度不是63px，而是63 * 1731（displayHeight）/ 1920 = 56，所以现在按照设计稿的尺寸添加，也无法显示成和设计稿一致的效果

--------------------------------------------

但是如果将displayHeight改为screenRealWidth，最后计算出来的结果将会是63 * 1920（screenRealWidth）/ 1920 = 56，现在设计稿的高度是1080x1920，但是如果现在我将布局里面View的高度设置成1920，最后显示出来的效果将会超出屏幕一部分，而那一部分的高度是“状态栏高度”+ “导航栏高度”之和。


所以现在无论设置为“displayHeight”还是“screenRealHeight”这个库仍然有这个严重的冲突BUG

**Comment by tcqq** [comment]
# 警告：此问题无法解决

**Comment by LXLYHM** [comment]
您好，我是李晓玲，邮件已查收，会尽快给您回复。谢谢！
